# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField()),
                ('last_name', models.CharField(max_length=255)),
                ('vk_id', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Rejected', 'Rejected'), ('Approved', 'Approved'), ('Research', 'Research'), ('Archieved', 'Archieved')], default='New', max_length=10)),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.User')),
            ],
        ),
    ]
