# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0004_auto_20180129_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AddField(
            model_name='crossprojectuser',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Project'),
        ),
        migrations.AddField(
            model_name='crossprojectuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
